name: Run Tests
on:
  workflow_call: # allows calling this workflow from another workflow
    secrets:
      ACCESS_KEY: { required: true }
      SECRET_KEY: { required: true }
      SESSION_TOKEN: { required: true }

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.SECRET_KEY }}
          aws-session-token: ${{secrets.SESSION_TOKEN}}
          aws-region: us-east-1